//go:build tray

package main

import (
	"context"
	"io"
	"log"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"fyne.io/systray"
)

// These tests characterise EVERY way cmd/aplexicatray can leave its event
// loop — i.e. every way it can reach systray.Quit() and exit 0 — WITHOUT the
// user clicking the Quit menu item. Exit 0 is load-bearing: the LaunchAgent
// generated by internal/trayinstall/trayinstall_darwin.go carries
// KeepAlive{SuccessfulExit:false}, so an exit-0 tray is never respawned.
//
// The channels driving clickLoop's select are systray.MenuItem.ClickedCh.
// A CLOSED Go channel makes its select case fire immediately and forever, so
// a closed ClickedCh would either quit the tray with no user interaction
// (miQuit) or spin the loop hot (any other case). newClickLoopTray builds a
// tray whose menu items are bare MenuItem values (only the exported
// ClickedCh field is set), so the loop can be driven without a live NSStatusItem.

func newClickLoopTray() *tray {
	item := func() *systray.MenuItem {
		return &systray.MenuItem{ClickedCh: make(chan struct{})}
	}
	t := &tray{
		miConflicts:        item(),
		miConflictMore:     item(),
		miPendingProjects:  item(),
		miPendingMore:      item(),
		miOpenWeb:          item(),
		miOpenDir:          item(),
		miPauseResume:      item(),
		miDaemonControl:    item(),
		miPauseFor:         item(),
		miPauseFor1h:       item(),
		miPauseFor4h:       item(),
		miPauseForRestart:  item(),
		miPauseForCustom:   item(),
		miOpenLogs:         item(),
		miOpenStatusReport: item(),
		miOpenConfig:       item(),
		miAbout:            item(),
		miQuit:             item(),
	}
	t.miConflictKids = make([]*systray.MenuItem, conflictSlotCount)
	for i := range t.miConflictKids {
		t.miConflictKids[i] = item()
	}
	t.miPendingKids = make([]*systray.MenuItem, pendingProjectSlotCount)
	for i := range t.miPendingKids {
		t.miPendingKids[i] = item()
	}
	return t
}

func runClickLoop(t *testing.T, tr *tray) <-chan struct{} {
	t.Helper()
	done := make(chan struct{})
	go func() {
		defer close(done)
		tr.clickLoop(t.TempDir())
	}()
	return done
}

// Baseline: with every ClickedCh merely IDLE (open, nothing sent), the loop
// must block forever. This is the invariant a fix must preserve.
func TestClickLoop_IdleChannelsNeverQuit(t *testing.T) {
	tr := newClickLoopTray()
	done := runClickLoop(t, tr)
	select {
	case <-done:
		t.Fatal("clickLoop returned with no click and no closed channel — " +
			"the tray would have called systray.Quit() and exited 0")
	case <-time.After(150 * time.Millisecond):
	}
}

// A CLOSED miQuit.ClickedCh is indistinguishable from the user picking Quit:
// the select case fires with no user interaction, clickLoop calls
// systray.Quit() and returns, and the process exits 0 → launchd's
// KeepAlive{SuccessfulExit:false} leaves the tray dead.
//
// This test documents the hazard as the code behaves TODAY. It is the
// characterisation half of "prove or refute": the mechanism is real in code.
// TestTrayNeverClosesMenuItemChannels below is the refutation half — nothing
// in this binary can actually close that channel, so this is not an active
// shutdown mechanism.
//
// A fix that hardens the loop (e.g. `case _, ok := <-t.miQuit.ClickedCh; if
// !ok { … }`) should flip this assertion to "did NOT return".
func TestClickLoop_ClosedQuitChannelQuitsWithoutAClick(t *testing.T) {
	tr := newClickLoopTray()
	done := runClickLoop(t, tr)
	close(tr.miQuit.ClickedCh)
	select {
	case <-done:
		// Current behaviour: a closed channel quits the tray.
	case <-time.After(2 * time.Second):
		t.Fatal("clickLoop did not return on a closed miQuit.ClickedCh; " +
			"the hardening this test characterises may already be in place — " +
			"update this test to assert the hardened behaviour")
	}
}

// A closed ClickedCh on any NON-quit case does not exit — it spins the select
// hot forever (here: miOpenDir with no watched dir, whose handler only logs
// and continues). Recorded so a fix is measured against both failure modes:
// no spurious quit AND no busy loop.
func TestClickLoop_ClosedNonQuitChannelSpinsHot(t *testing.T) {
	previous := log.Writer()
	log.SetOutput(io.Discard)
	defer log.SetOutput(previous)

	tr := newClickLoopTray()
	done := runClickLoop(t, tr)
	close(tr.miOpenDir.ClickedCh) // watchedDir is "" → handler logs and continues

	select {
	case <-done:
		t.Fatal("clickLoop returned on a closed non-quit channel — expected a hot loop")
	case <-time.After(50 * time.Millisecond):
	}

	// Stop the spinning goroutine so it does not burn a core for the rest of
	// the test binary's life.
	close(tr.miQuit.ClickedCh)
	select {
	case <-done:
	case <-time.After(2 * time.Second):
		t.Fatal("clickLoop did not stop after closing miQuit.ClickedCh")
	}
}

// REFUTATION. fyne.io/systray v1.12.1 closes a MenuItem.ClickedCh in exactly
// one place — MenuItem.Remove() (systray.go:274), which ResetMenu() also
// drives. The tray uses the pre-allocate + Show/Hide pattern and never calls
// either, so no ClickedCh in this binary can ever be closed. Guard that
// property so the (unreachable) spurious-quit hazard above stays unreachable.
func TestTrayNeverClosesMenuItemChannels(t *testing.T) {
	entries, err := os.ReadDir(".")
	if err != nil {
		t.Fatalf("read package dir: %v", err)
	}
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || filepath.Ext(name) != ".go" || strings.HasSuffix(name, "_test.go") {
			continue
		}
		body, err := os.ReadFile(name)
		if err != nil {
			t.Fatalf("read %s: %v", name, err)
		}
		source := string(body)
		for _, closer := range []string{".Remove()", "systray.ResetMenu("} {
			if strings.Contains(source, closer) {
				t.Errorf("%s calls %s — that closes MenuItem.ClickedCh "+
					"(fyne.io/systray systray.go:274), which makes clickLoop's "+
					"select fire its case forever and quit the tray with no user click",
					name, closer)
			}
		}
	}
}

// tray.run is the other route to systray.Quit(). Both of its non-click exits
// are gated on the SAME context: ctx.Done() quits directly, and the snapshots
// channel is closed only by main's supervisor goroutine, which returns only
// once ctx is cancelled (supervise.go:42-58). So every spurious clean exit of
// the shipped tray traces back to something cancelling that context — SIGINT/
// SIGTERM (main.go:186) or the traycontrol "quit-for-update" command
// (internal/traycontrol/control.go:112-116 → main.go:193).
func TestRun_ContextCancelQuits(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	snapshots := make(chan StatusSnapshot)
	done := make(chan struct{})
	tr := newClickLoopTray()
	go func() {
		defer close(done)
		tr.run(ctx, snapshots, time.Hour, time.Hour)
	}()
	select {
	case <-done:
		cancel()
		t.Fatal("run returned before the context was cancelled")
	case <-time.After(50 * time.Millisecond):
	}
	cancel()
	select {
	case <-done:
	case <-time.After(2 * time.Second):
		t.Fatal("run did not return (systray.Quit) on ctx cancellation")
	}
}

// The closed-snapshots exit exists too, but it is strictly downstream of a
// cancelled context in the shipped wiring (main.go:203-213).
func TestRun_ClosedSnapshotsQuits(t *testing.T) {
	snapshots := make(chan StatusSnapshot)
	done := make(chan struct{})
	tr := newClickLoopTray()
	go func() {
		defer close(done)
		tr.run(context.Background(), snapshots, time.Hour, time.Hour)
	}()
	close(snapshots)
	select {
	case <-done:
	case <-time.After(2 * time.Second):
		t.Fatal("run did not return (systray.Quit) on a closed snapshots channel")
	}
}
