// Package releasetrust holds the public, compile-time release contract used by
// the advisory updater and repository drift guards.
//
// AWS KMS is the signing authority. GitHub supplies short-lived OIDC
// credentials to the isolated signing job and hosts the resulting release,
// but neither GitHub nor Fulcio signs an Aplexica release asset. Users verify
// the manifest and provenance with the reviewed public key distributed with
// this repository. These constants name the public objects; no credential,
// account identifier, role ARN, KMS URI, or private infrastructure detail is
// compiled into the product.
package releasetrust

const (
	// Repository is GitHub's canonical-cased slug. It is used only to derive
	// public release URLs and provenance source identity.
	Repository = "Aplexica/Aplexica"

	// ReleaseWorkflowPath is stable because the AWS OIDC trust and public
	// provenance both bind the release workflow. Moving it is an authority
	// migration, not a refactor.
	ReleaseWorkflowPath = ".github/workflows/release.yml"

	// ChecksumsAsset covers the ten build artifacts. ChecksumsBundle contains
	// the KMS-backed cosign signature over that manifest.
	ChecksumsAsset  = "SHA256SUMS"
	ChecksumsBundle = "SHA256SUMS.sigstore.json"

	// ProvenanceBundle contains the KMS-backed DSSE signature over the exact
	// ten-subject in-toto statement generated by tools/releaseprovenance.
	ProvenanceBundle = "aplexica.provenance.sigstore.json"

	// PublicKey is the reviewed PEM trust anchor. It is source-controlled and
	// never downloaded from the release being verified.
	PublicKey = "aplexica-release.pub"

	InTotoStatementType = "https://in-toto.io/Statement/v1"
	SLSAProvenanceType  = "https://slsa.dev/provenance/v1"
)
