package config

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

// ─────────────────────────────────────────────────────────────────────
// Schema engine extension: "float" + "int-or-all" types.
//
// The `aplexica config schema|docs|validate` commands consume the
// SchemaMarkdown()/SchemaJSON() wire surface. The golden test below
// freezes the rendering of the EXISTING entries so the float/int-or-all
// additions can only be additive — an accidental change to how a
// pre-existing key renders fails here.
// ─────────────────────────────────────────────────────────────────────

// goldenExistingMarkdownRows is the byte-exact set of Markdown table rows
// for the older schema entries. `_meta.schema_version` is intentionally
// omitted because a later schema update bumps its default; every other
// pre-existing key must render unchanged.
var goldenExistingMarkdownRows = []string{
	"| `daemon.project_scan_interval` | duration | `60m` | [1m..24h] (0 disables) |  | yes | How often the daemon scans for project repos matching pending artifacts (BRD-02 §4.13.4). Set to '0s' to disable. |",
	"| `daemon.project_scan_max_depth` | int | `6` | [1..16] |  | yes | Maximum directory depth the project scan descends below each root. |",
	"| `daemon.project_scan_roots` | string-array | `[]` |  |  | yes | Absolute paths the project scan walks. Empty list falls back to pending.DefaultScanRoots() ($HOME). |",
	"| `daemon.project_scan_warmup` | duration | `10s` | [0s..60s] (0 disables) |  | yes | Warm-up grace period after daemon start before the first project-scan tick fires. |",
	"| `daemon.quiet_period` | duration | `500ms` | [50ms..10s] |  |  | Watcher debounce window: minimum quiet time between filesystem events before the daemon acts on a coalesced batch. |",
	"| `daemon.guard_window` | duration | `5s` | [100ms..60s] |  |  | Recursion-guard window: how long to suppress inbound events generated by an outbound write (loop prevention). |",
	"| `retention.snapshot_min_events` | int | `100` | [10..10000] | events |  | Minimum events on an artifact's chain before a snapshot becomes eligible (BRD-03 §4.8.2). |",
	"| `retention.snapshot_min_age` | duration | `7d` | [1h..30d] |  |  | Minimum age of the artifact's HEAD event before a snapshot is taken. |",
	"| `retention.prune_keep_tail` | int | `10` | [0..1000] | events |  | Pre-snapshot events to keep in the on-disk log after pruning. Acts as a tail-buffer for replay debugging. |",
	"| `tray.refresh_interval` | duration | `5s` | [1s..30s] |  |  | Tray status indicator refresh cadence. |",
	"| `tray.active_window` | duration | `60s` | [1s..10m] |  |  | How long after the last filesystem event before the tray switches from 'active' back to 'idle'. |",
	"| `tray.paused_window` | duration | `10m` | [1m..1h] |  |  | Threshold after which the tray badges 'paused' rather than 'idle'. |",
	"| `conflicts.ttl` | duration | `30d` | [24h..90d] |  |  | Per-artifact retention of conflict-detection records before GC. |",
	"| `branches.auto_archive_after_days` | int | `90` | [0..3650] (0 disables) | days |  | Branches with no events newer than this are auto-archived (BRD-04 §4.3.1 / FR-04.14). Set to 0 to disable. |",
	"| `branches.auto_archive_interval` | duration | `24h` | [5m..168h] |  |  | How often the daemon runs the branch auto-archive lifecycle pass. |",
	"| `secrets.default_sync_secrets` | bool | `false` |  |  |  | Default value of `syncSecrets` on newly-imported tool artifacts (FR-02.16). |",
	"| `metrics.enabled` | bool | `false` |  |  | yes | Enable the Prometheus /metrics endpoint (FR-03.14). Off by default. |",
	"| `metrics.listen` | string | `127.0.0.1:9090` |  |  | yes | host:port for the metrics endpoint. FR-10.4 requires loopback-only by default; bind elsewhere only with explicit operator intent. |",
	"| `bundle.default_filename` | string | `aplexica-backup-{date}.tar.gz` |  |  |  | Default bundle filename when `aplexica backup` is invoked without an explicit path. '{date}' is substituted with the local YYYY-MM-DD date. |",
	"| `bundle.compression_level` | int | `6` | [1..9] |  |  | Default gzip compression level for bundle export. 1=fastest/largest, 9=slowest/smallest. |",
	"| `log.rotate_keep` | int | `30` | [1..365] |  |  | How many rotated log files the daemon keeps before deleting the oldest (FR-10.3). |",
	"| `log.rotate_at` | string | `midnight-local` | midnight-local \\| midnight-utc |  |  | When the daemon rotates its log files. |",
	"| `log.doctor_tail_bytes` | int | `65536` | [1024..1048576] | bytes |  | Bytes of the most recent log included in `aplexica doctor` reports (FR-10.2). |",
}

// goldenExistingJSONObjects is the byte-exact (pretty-printed, 2-space)
// JSON object for each pre-existing key. The whole SchemaJSON() document
// embeds these verbatim; asserting on the substring keeps the test
// additive-tolerant while pinning the per-key shape.
var goldenExistingJSONObjects = []string{
	`  {
    "key": "daemon.project_scan_max_depth",
    "type": "int",
    "default": "6",
    "description": "Maximum directory depth the project scan descends below each root.",
    "min": 1,
    "max": 16,
    "restart_required": true
  }`,
	`  {
    "key": "retention.snapshot_min_events",
    "type": "int",
    "default": "100",
    "description": "Minimum events on an artifact's chain before a snapshot becomes eligible (BRD-03 §4.8.2).",
    "unit": "events",
    "min": 10,
    "max": 10000
  }`,
	`  {
    "key": "log.rotate_at",
    "type": "string",
    "default": "midnight-local",
    "description": "When the daemon rotates its log files.",
    "valid_values": [
      "midnight-local",
      "midnight-utc"
    ]
  }`,
}

func TestSchemaMarkdown_ExistingEntriesUnchanged_Golden(t *testing.T) {
	md := SchemaMarkdown()
	for _, row := range goldenExistingMarkdownRows {
		require.Contains(t, md, row,
			"existing schema row must render byte-for-byte unchanged (additive-only); missing:\n%s", row)
	}
}

func TestSchemaJSON_ExistingEntriesUnchanged_Golden(t *testing.T) {
	b, err := SchemaJSON()
	require.NoError(t, err)
	js := string(b)
	for _, obj := range goldenExistingJSONObjects {
		require.Contains(t, js, obj,
			"existing schema JSON object must render byte-for-byte unchanged (additive-only); missing:\n%s", obj)
	}
}

// ─────────────────────────────────────────────────────────────────────
// "float" type: range check honoring AllowZero (0 disables the range,
// like the int case).
// ─────────────────────────────────────────────────────────────────────

func TestCheckEntry_Float_AcceptsInRange(t *testing.T) {
	e := SchemaEntry{
		Key:      "x.f",
		Type:     "float",
		MinFloat: floatPtr(0),
		MaxFloat: floatPtr(1),
	}
	require.Equal(t, "", checkEntry(e, "0.85"))
	require.Equal(t, "", checkEntry(e, "0"))
	require.Equal(t, "", checkEntry(e, "1"))
}

func TestCheckEntry_Float_RejectsAboveMax(t *testing.T) {
	e := SchemaEntry{
		Key:      "x.f",
		Type:     "float",
		MinFloat: floatPtr(0),
		MaxFloat: floatPtr(1),
	}
	msg := checkEntry(e, "1.5")
	require.NotEmpty(t, msg)
	require.Contains(t, msg, "above maximum")
}

func TestCheckEntry_Float_RejectsBelowMin(t *testing.T) {
	e := SchemaEntry{
		Key:      "x.f",
		Type:     "float",
		MinFloat: floatPtr(0.5),
		MaxFloat: floatPtr(1),
	}
	msg := checkEntry(e, "0.1")
	require.NotEmpty(t, msg)
	require.Contains(t, msg, "below minimum")
}

func TestCheckEntry_Float_RejectsNonNumeric(t *testing.T) {
	e := SchemaEntry{Key: "x.f", Type: "float"}
	msg := checkEntry(e, "abc")
	require.NotEmpty(t, msg)
	require.Contains(t, msg, "expected float")
}

func TestCheckEntry_Float_AllowZeroBypassesRange(t *testing.T) {
	// store_max_gb shape: 0 = unlimited is accepted via AllowZero even
	// though Min would otherwise reject it.
	e := SchemaEntry{
		Key:       "x.f",
		Type:      "float",
		MinFloat:  floatPtr(1),
		MaxFloat:  floatPtr(100),
		AllowZero: true,
	}
	require.Equal(t, "", checkEntry(e, "0"),
		"AllowZero must accept the 0 sentinel outside [min..max]")
	require.Equal(t, "", checkEntry(e, "0.0"))
	// A genuinely out-of-range non-zero value still fails.
	require.NotEmpty(t, checkEntry(e, "0.5"))
}

// ─────────────────────────────────────────────────────────────────────
// "int-or-all" type: literal "all" OR any int >= 0.
// ─────────────────────────────────────────────────────────────────────

func TestCheckEntry_IntOrAll_AcceptsAll(t *testing.T) {
	e := SchemaEntry{Key: "x.n", Type: "int-or-all"}
	require.Equal(t, "", checkEntry(e, "all"))
}

func TestCheckEntry_IntOrAll_AcceptsNonNegativeInt(t *testing.T) {
	e := SchemaEntry{Key: "x.n", Type: "int-or-all"}
	require.Equal(t, "", checkEntry(e, "5"))
	require.Equal(t, "", checkEntry(e, "0"))
}

func TestCheckEntry_IntOrAll_RejectsNegative(t *testing.T) {
	e := SchemaEntry{Key: "x.n", Type: "int-or-all"}
	msg := checkEntry(e, "-1")
	require.NotEmpty(t, msg)
}

func TestCheckEntry_IntOrAll_RejectsNonNumeric(t *testing.T) {
	e := SchemaEntry{Key: "x.n", Type: "int-or-all"}
	msg := checkEntry(e, "foo")
	require.NotEmpty(t, msg)
}

// TestCheckEntry_IntOrAll_HonorsMinInt covers FR-03.25's floor: when an
// int-or-all entry sets MinInt (keep_last_n_snapshots uses MinInt=2), the
// numeric branch must reject values below it while the "all" sentinel still
// passes. A bare entry with no MinInt keeps the floor-0 behavior (the other
// int-or-all tests above).
func TestCheckEntry_IntOrAll_HonorsMinInt(t *testing.T) {
	e := SchemaEntry{Key: "x.n", Type: "int-or-all", MinInt: intPtr(2)}
	require.Equal(t, "", checkEntry(e, "all"), `"all" sentinel bypasses MinInt`)
	require.Equal(t, "", checkEntry(e, "2"), "value at MinInt floor is accepted")
	require.Equal(t, "", checkEntry(e, "9"), "value above MinInt floor is accepted")
	require.NotEmpty(t, checkEntry(e, "1"), "value below MinInt floor must be rejected")
	require.NotEmpty(t, checkEntry(e, "0"), "zero below MinInt floor must be rejected")
}

// ─────────────────────────────────────────────────────────────────────
// Rendering: SchemaMarkdown/SchemaJSON must surface the new ranges.
// ─────────────────────────────────────────────────────────────────────

func TestSchemaMarkdown_RendersFloatRangeAndIntOrAll(t *testing.T) {
	// Drive the render functions directly against synthetic entries so
	// the assertion doesn't depend on PR2 keys existing yet. We render a
	// one-row table by temporarily checking the package render helpers
	// via a constructed slice through the public funcs is not possible
	// (Schema is package-global); instead assert the range helper output
	// through markdownRange.
	fe := SchemaEntry{Key: "x.f", Type: "float", MinFloat: floatPtr(0), MaxFloat: floatPtr(1)}
	require.Equal(t, "[0..1]", markdownRange(fe))

	fz := SchemaEntry{Key: "x.f", Type: "float", MinFloat: floatPtr(1), MaxFloat: floatPtr(100), AllowZero: true}
	require.True(t, strings.Contains(markdownRange(fz), "(0 disables)"))
}
