package config

import (
	"encoding/json"
	"fmt"
	"sort"
	"strconv"
	"strings"
	"time"
)

// Schema is the canonical description of every tunable parameter — the
// FR-10.9 deliverable ("Every parameter MUST have a JSON Schema entry
// describing its type, range, default value, unit, and human-readable
// description"). The shipped binary embeds Schema; `aplexica config
// schema` emits it as JSON; `aplexica config docs` renders it as
// Markdown.
//
// The schema is hand-authored alongside defaults.toml. Adding a new key
// is a two-step change: drop the default into defaults.toml AND add the
// matching Schema entry below. Validate() consults Schema to range-check
// every user-supplied value.
type SchemaEntry struct {
	Key             string   `json:"key"`
	Type            string   `json:"type"` // duration | int | int-or-all | float | bool | string | string-array
	Default         string   `json:"default"`
	Description     string   `json:"description"`
	Unit            string   `json:"unit,omitempty"`
	MinInt          *int64   `json:"min,omitempty"`
	MaxInt          *int64   `json:"max,omitempty"`
	MinFloat        *float64 `json:"min_float,omitempty"`
	MaxFloat        *float64 `json:"max_float,omitempty"`
	MinDuration     string   `json:"min_duration,omitempty"`
	MaxDuration     string   `json:"max_duration,omitempty"`
	ValidValues     []string `json:"valid_values,omitempty"`
	RestartRequired bool     `json:"restart_required,omitempty"`
	// AllowZero, when true, permits "0" / "0s" / "0.0" as a sentinel
	// meaning "feature disabled" even when MinInt/MinFloat/MinDuration
	// would otherwise reject zero (e.g. project_scan_interval = "0s"
	// disables the scan; retention.store_max_gb = 0 means unlimited).
	AllowZero bool `json:"allow_zero,omitempty"`
}

func intPtr(v int64) *int64       { return &v }
func floatPtr(v float64) *float64 { return &v }

// Schema is the V1 schema table. Order matches defaults.toml visually
// for ease of cross-referencing.
var Schema = []SchemaEntry{
	// [daemon]
	{
		Key:             "daemon.project_scan_interval",
		Type:            "duration",
		Default:         "60m",
		Description:     "How often the daemon scans for project repos matching pending artifacts (BRD-02 §4.13.4). Set to '0s' to disable.",
		MinDuration:     "1m",
		MaxDuration:     "24h",
		AllowZero:       true,
		RestartRequired: true,
	},
	{
		Key:             "daemon.project_scan_max_depth",
		Type:            "int",
		Default:         "6",
		Description:     "Maximum directory depth the project scan descends below each root.",
		MinInt:          intPtr(1),
		MaxInt:          intPtr(16),
		RestartRequired: true,
	},
	{
		Key:             "daemon.project_scan_roots",
		Type:            "string-array",
		Default:         "[]",
		Description:     "Absolute paths the project scan walks. Empty list falls back to pending.DefaultScanRoots() ($HOME).",
		RestartRequired: true,
	},
	{
		Key:             "daemon.project_scan_warmup",
		Type:            "duration",
		Default:         "10s",
		Description:     "Warm-up grace period after daemon start before the first project-scan tick fires.",
		MinDuration:     "0s",
		MaxDuration:     "60s",
		AllowZero:       true,
		RestartRequired: true,
	},
	{
		Key:         "daemon.quiet_period",
		Type:        "duration",
		Default:     "500ms",
		Description: "Watcher debounce window: minimum quiet time between filesystem events before the daemon acts on a coalesced batch.",
		MinDuration: "50ms",
		MaxDuration: "10s",
	},
	{
		Key:         "daemon.guard_window",
		Type:        "duration",
		Default:     "5s",
		Description: "Recursion-guard window: how long to suppress inbound events generated by an outbound write (loop prevention).",
		MinDuration: "100ms",
		MaxDuration: "60s",
	},
	{
		Key:             "daemon.claude_session_scan_window",
		Type:            "duration",
		Default:         "15m",
		Description:     "How long an active Claude Code transcript remains in the daemon's hot session poll set after import or remote materialization.",
		MinDuration:     "1m",
		MaxDuration:     "60m",
		RestartRequired: true,
	},
	// [limits]
	{
		Key:             "limits.max_artifact_size_mb",
		Type:            "int",
		Default:         "64",
		Description:     "Maximum size of a single native artifact file the daemon will ingest (BRD-03 §4.3/§5); larger files are refused before parse. Agent session transcripts use limits.max_session_file_mb instead. -1 disables the cap.",
		Unit:            "MB",
		MinInt:          intPtr(-1),
		MaxInt:          intPtr(10240),
		RestartRequired: true,
	},
	{
		Key:             "limits.max_session_file_mb",
		Type:            "int",
		Default:         "512",
		Description:     "Maximum size of a single agent session transcript (Claude Code / Codex JSONL) the daemon will ingest; larger transcripts are refused before parse. Separate from the generic artifact cap because aligned-chain sync replicates transcripts as per-turn deltas. -1 disables the cap.",
		Unit:            "MB",
		MinInt:          intPtr(-1),
		MaxInt:          intPtr(10240),
		RestartRequired: true,
	},
	// [retention]
	{
		Key:         "retention.snapshot_min_events",
		Type:        "int",
		Default:     "100",
		Description: "Minimum events on an artifact's chain before a snapshot becomes eligible (BRD-03 §4.8.2).",
		Unit:        "events",
		MinInt:      intPtr(10),
		MaxInt:      intPtr(10000),
	},
	{
		Key:         "retention.snapshot_min_age",
		Type:        "duration",
		Default:     "7d",
		Description: "Minimum age of the artifact's HEAD event before a snapshot is taken.",
		MinDuration: "1h",
		MaxDuration: "30d",
	},
	{
		Key:         "retention.prune_keep_tail",
		Type:        "int",
		Default:     "10",
		Description: "Pre-snapshot events to keep in the on-disk log after pruning. Acts as a tail-buffer for replay debugging.",
		Unit:        "events",
		MinInt:      intPtr(0),
		MaxInt:      intPtr(1000),
	},
	// [retention] — disk-pressure / attachment-eviction policy (BRD-03 §4.8.4).
	{
		Key:         "retention.store_max_gb",
		Type:        "float",
		Default:     "0",
		Description: "Hard cap on the canonical store size (BRD-03 §4.8.4 specifies 10). Default 0 = unlimited (no disk-pressure trigger, no emergency ingest refusal); set a finite cap only alongside a finite keep_last_n_snapshots.",
		Unit:        "GB",
		MinFloat:    floatPtr(0),
		MaxFloat:    floatPtr(10000),
		AllowZero:   true,
	},
	{
		Key:         "retention.store_high_watermark",
		Type:        "float",
		Default:     "0.80",
		Description: "Fraction of store_max_gb at which emergency pruning (force-snapshot + aggressive prune) triggers (BRD-03 §4.8.4).",
		MinFloat:    floatPtr(0),
		MaxFloat:    floatPtr(1),
	},
	{
		Key:         "retention.store_emergency_quota",
		Type:        "float",
		Default:     "0.95",
		Description: "Fraction of store_max_gb above which new ingestion is refused (BRD-03 §4.8.4). Must be >= store_high_watermark.",
		MinFloat:    floatPtr(0),
		MaxFloat:    floatPtr(1),
	},
	{
		Key:         "retention.attachments_only",
		Type:        "bool",
		Default:     "true",
		Description: "OSS default: at the watermark, evict attachment bytes only (text stays). false = full event pruning (BRD-03 §4.8.3).",
	},
	{
		Key:         "retention.attachment_min_age_days",
		Type:        "int",
		Default:     "30",
		Description: "Attachments younger than this are protected from eviction (BRD-03 §4.8.3).",
		Unit:        "days",
		MinInt:      intPtr(0),
		MaxInt:      intPtr(3650),
	},
	{
		Key:         "retention.keep_last_n_snapshots",
		Type:        "int-or-all",
		Default:     "all",
		Description: "'all' (default) keeps every snapshot and disables pre-snapshot history compaction; an integer (floor 2) caps retained snapshots per artifact — older snapshot history is compacted out of the active log, anchored at the Nth-most-recent snapshot (FR-03.25, BRD-03 §4.8.4).",
		Unit:        "snapshots",
		MinInt:      intPtr(2),
	},
	{
		Key:         "retention.pin_tags",
		Type:        "string-array",
		Default:     `["pinned", "keep-forever"]`,
		Description: "Artifacts carrying any of these tags are exempt from all pruning and eviction (BRD-03 §4.8.4).",
	},
	{
		Key:         "retention.snapshot_after_events.conversation",
		Type:        "int",
		Default:     "100",
		Description: "Per-kind snapshot cadence: events on a conversation's chain before a snapshot is due (BRD-03 §4.8.1/§4.8.4).",
		Unit:        "events",
		MinInt:      intPtr(1),
		MaxInt:      intPtr(100000),
	},
	{
		Key:         "retention.snapshot_after_events.memory",
		Type:        "int",
		Default:     "50",
		Description: "Per-kind snapshot cadence: events on a memory artifact's chain before a snapshot is due (BRD-03 §4.8.4).",
		Unit:        "events",
		MinInt:      intPtr(1),
		MaxInt:      intPtr(100000),
	},
	{
		Key:         "retention.snapshot_after_events.skill",
		Type:        "int",
		Default:     "50",
		Description: "Per-kind snapshot cadence: events on a skill artifact's chain before a snapshot is due (BRD-03 §4.8.4).",
		Unit:        "events",
		MinInt:      intPtr(1),
		MaxInt:      intPtr(100000),
	},
	{
		Key:         "retention.snapshot_after_events.tool",
		Type:        "int",
		Default:     "50",
		Description: "Per-kind snapshot cadence: events on a tool artifact's chain before a snapshot is due (BRD-03 §4.8.4).",
		Unit:        "events",
		MinInt:      intPtr(1),
		MaxInt:      intPtr(100000),
	},
	{
		Key:         "retention.snapshot_after_time.conversation",
		Type:        "duration",
		Default:     "24h",
		Description: "Per-kind snapshot cadence: max age of a conversation's HEAD before a snapshot is due (BRD-03 §4.8.4).",
		MinDuration: "1h",
		MaxDuration: "365d",
	},
	{
		Key:         "retention.snapshot_after_time.memory",
		Type:        "duration",
		Default:     "7d",
		Description: "Per-kind snapshot cadence: max age of a memory artifact's HEAD before a snapshot is due (BRD-03 §4.8.4).",
		MinDuration: "1h",
		MaxDuration: "365d",
	},
	{
		Key:         "retention.snapshot_after_time.skill",
		Type:        "duration",
		Default:     "7d",
		Description: "Per-kind snapshot cadence: max age of a skill artifact's HEAD before a snapshot is due (BRD-03 §4.8.4).",
		MinDuration: "1h",
		MaxDuration: "365d",
	},
	{
		Key:         "retention.snapshot_after_time.tool",
		Type:        "duration",
		Default:     "7d",
		Description: "Per-kind snapshot cadence: max age of a tool artifact's HEAD before a snapshot is due (BRD-03 §4.8.4).",
		MinDuration: "1h",
		MaxDuration: "365d",
	},
	// [tray]
	{
		Key:         "tray.refresh_interval",
		Type:        "duration",
		Default:     "5s",
		Description: "Tray status indicator refresh cadence.",
		MinDuration: "1s",
		MaxDuration: "30s",
	},
	{
		Key:         "tray.active_window",
		Type:        "duration",
		Default:     "60s",
		Description: "How long after the last filesystem event before the tray switches from 'active' back to 'idle'.",
		MinDuration: "1s",
		MaxDuration: "10m",
	},
	{
		Key:         "tray.paused_window",
		Type:        "duration",
		Default:     "10m",
		Description: "Threshold after which the tray badges 'paused' rather than 'idle'.",
		MinDuration: "1m",
		MaxDuration: "1h",
	},
	// [conflicts]
	{
		Key:         "conflicts.ttl",
		Type:        "duration",
		Default:     "30d",
		Description: "Per-artifact retention of conflict-detection records before GC.",
		MinDuration: "24h",
		MaxDuration: "90d",
	},
	// [branches] — BRD-04 §4.3.1 branch auto-archival.
	{
		Key:         "branches.auto_archive_after_days",
		Type:        "int",
		Default:     "90",
		Description: "Branches with no events newer than this are auto-archived (BRD-04 §4.3.1 / FR-04.14). Set to 0 to disable.",
		Unit:        "days",
		MinInt:      intPtr(0),
		MaxInt:      intPtr(3650),
		AllowZero:   true,
	},
	{
		Key:         "branches.auto_archive_interval",
		Type:        "duration",
		Default:     "24h",
		Description: "How often the daemon runs the branch auto-archive lifecycle pass.",
		MinDuration: "5m",
		MaxDuration: "168h",
	},
	// [secrets]
	{
		Key:         "secrets.default_sync_secrets",
		Type:        "bool",
		Default:     "false",
		Description: "Default value of `syncSecrets` on newly-imported tool artifacts (FR-02.16).",
	},
	// [metrics] — FR-03.14 / FR-10.4
	{
		Key:             "metrics.enabled",
		Type:            "bool",
		Default:         "false",
		Description:     "Enable the Prometheus /metrics endpoint (FR-03.14). Off by default.",
		RestartRequired: true,
	},
	{
		Key:             "metrics.listen",
		Type:            "string",
		Default:         "127.0.0.1:9090",
		Description:     "host:port for the metrics endpoint. FR-10.4 requires loopback-only by default; bind elsewhere only with explicit operator intent.",
		RestartRequired: true,
	},
	// [bundle]
	{
		Key:         "bundle.default_filename",
		Type:        "string",
		Default:     "aplexica-backup-{date}.tar.gz",
		Description: "Default bundle filename when `aplexica backup` is invoked without an explicit path. '{date}' is substituted with the local YYYY-MM-DD date.",
	},
	{
		Key:         "bundle.compression_level",
		Type:        "int",
		Default:     "6",
		Description: "Default gzip compression level for bundle export. 1=fastest/largest, 9=slowest/smallest.",
		MinInt:      intPtr(1),
		MaxInt:      intPtr(9),
	},
	// [log]
	{
		Key:         "log.rotate_keep",
		Type:        "int",
		Default:     "30",
		Description: "How many rotated log files the daemon keeps before deleting the oldest (FR-10.3).",
		MinInt:      intPtr(1),
		MaxInt:      intPtr(365),
	},
	{
		Key:         "log.rotate_at",
		Type:        "string",
		Default:     "midnight-local",
		Description: "When the daemon rotates its log files.",
		ValidValues: []string{"midnight-local", "midnight-utc"},
	},
	{
		Key:         "log.doctor_tail_bytes",
		Type:        "int",
		Default:     "65536",
		Description: "Bytes of the most recent log included in `aplexica doctor` reports (FR-10.2).",
		Unit:        "bytes",
		MinInt:      intPtr(1024),
		MaxInt:      intPtr(1048576),
	},
	// [_meta]
	{
		Key:         "_meta.schema_version",
		Type:        "int",
		Default:     "7",
		Description: "Bumped whenever the defaults schema gains a new key or changes a semantic.",
		MinInt:      intPtr(1),
	},
}

// schemaByKey is a lazy lookup map.
var schemaByKey = func() map[string]SchemaEntry {
	m := make(map[string]SchemaEntry, len(Schema))
	for _, e := range Schema {
		m[e.Key] = e
	}
	return m
}()

// knownSchemaSections returns the set of section names that appear in
// the schema. Used by applyEnv to disambiguate APLEXICA_<SECTION>_<FIELD>
// when field names contain underscores.
func knownSchemaSections() map[string]struct{} {
	out := map[string]struct{}{}
	for _, e := range Schema {
		if idx := strings.IndexByte(e.Key, '.'); idx > 0 {
			out[e.Key[:idx]] = struct{}{}
		}
	}
	return out
}

// SchemaJSON returns the schema as pretty-printed JSON. `aplexica config
// schema` writes this to stdout.
func SchemaJSON() ([]byte, error) {
	return json.MarshalIndent(Schema, "", "  ")
}

// SchemaMarkdown renders the schema as a human-readable Markdown table.
// `aplexica config docs` emits this.
func SchemaMarkdown() string {
	var b strings.Builder
	b.WriteString("# Aplexica configuration schema\n\n")
	b.WriteString("This document is generated from `internal/config/schema.go`. Every tunable parameter is listed here with its type, default, valid range, and units. Override precedence is shipped → system → user → project → env → CLI; see `aplexica config show` for the layer that set each effective value.\n\n")
	b.WriteString("| Key | Type | Default | Range | Unit | Restart? | Description |\n")
	b.WriteString("|---|---|---|---|---|---|---|\n")
	// Stable order matching Schema slice (already grouped by section).
	for _, e := range Schema {
		rng := markdownRange(e)
		restart := ""
		if e.RestartRequired {
			restart = "yes"
		}
		fmt.Fprintf(&b, "| `%s` | %s | `%s` | %s | %s | %s | %s |\n",
			e.Key, e.Type, e.Default, rng, e.Unit, restart, e.Description)
	}
	return b.String()
}

// markdownRange renders the human-readable range cell for one entry.
// Pulled out of SchemaMarkdown so the float / int-or-all additions are
// exercisable in isolation and the existing-key golden test stays
// byte-stable.
func markdownRange(e SchemaEntry) string {
	rng := ""
	switch {
	case e.MinInt != nil && e.MaxInt != nil:
		rng = fmt.Sprintf("[%d..%d]", *e.MinInt, *e.MaxInt)
	case e.MinInt != nil:
		rng = fmt.Sprintf("≥%d", *e.MinInt)
	case e.MaxInt != nil:
		rng = fmt.Sprintf("≤%d", *e.MaxInt)
	case e.MinFloat != nil && e.MaxFloat != nil:
		rng = fmt.Sprintf("[%s..%s]", trimFloat(*e.MinFloat), trimFloat(*e.MaxFloat))
	case e.MinFloat != nil:
		rng = "≥" + trimFloat(*e.MinFloat)
	case e.MaxFloat != nil:
		rng = "≤" + trimFloat(*e.MaxFloat)
	case e.MinDuration != "" && e.MaxDuration != "":
		rng = fmt.Sprintf("[%s..%s]", e.MinDuration, e.MaxDuration)
	case e.MinDuration != "":
		rng = "≥" + e.MinDuration
	case e.MaxDuration != "":
		rng = "≤" + e.MaxDuration
	case len(e.ValidValues) > 0:
		rng = strings.Join(e.ValidValues, " \\| ")
	}
	if e.AllowZero && rng != "" {
		rng += " (0 disables)"
	}
	return rng
}

// trimFloat renders a float64 range bound without trailing zeros so
// 0.0 → "0", 0.85 → "0.85", 1.0 → "1" (matches how the int bounds and
// the BRD's prose render the watermark fractions).
func trimFloat(f float64) string {
	return strconv.FormatFloat(f, 'f', -1, 64)
}

// SchemaValidate checks an Effective configuration against the Schema.
// Returns a sorted, deduplicated list of human-readable error strings —
// one per violation. The empty slice means "ok".
//
// Unknown keys (present in the Effective but absent from Schema) are
// reported as warnings, not failures, per BRD-10 §10.2: "Unknown keys
// (typos, deprecated keys from old versions) produce warnings at
// startup, not failures." Warnings are returned in the second slice.
func SchemaValidate(eff *Effective) (errs []string, warns []string) {
	for k, v := range eff.Values {
		entry, ok := schemaByKey[k]
		if !ok {
			warns = append(warns, fmt.Sprintf("unknown key %q (typo, or deprecated since this binary's schema)", k))
			continue
		}
		if msg := checkEntry(entry, v); msg != "" {
			errs = append(errs, fmt.Sprintf("%s: %s", k, msg))
		}
	}
	sort.Strings(errs)
	sort.Strings(warns)
	return errs, warns
}

func checkEntry(e SchemaEntry, v string) string {
	switch e.Type {
	case "int":
		n, err := strconv.ParseInt(v, 10, 64)
		if err != nil {
			return fmt.Sprintf("expected int, got %q", v)
		}
		if e.MinInt != nil && n < *e.MinInt {
			return fmt.Sprintf("value %d is below minimum %d", n, *e.MinInt)
		}
		if e.MaxInt != nil && n > *e.MaxInt {
			return fmt.Sprintf("value %d is above maximum %d", n, *e.MaxInt)
		}
	case "int-or-all":
		// The literal "all" is the keep-everything sentinel
		// (retention.keep_last_n_snapshots). Otherwise an int honoring the
		// entry's MinInt/MaxInt; when MinInt is unset the implicit floor is 0.
		if v == "all" {
			return ""
		}
		n, err := strconv.ParseInt(v, 10, 64)
		if err != nil {
			return fmt.Sprintf("expected int or 'all', got %q", v)
		}
		floor := int64(0)
		if e.MinInt != nil {
			floor = *e.MinInt
		}
		if n < floor {
			return fmt.Sprintf("value %d is below minimum %d", n, floor)
		}
		if e.MaxInt != nil && n > *e.MaxInt {
			return fmt.Sprintf("value %d is above maximum %d", n, *e.MaxInt)
		}
	case "float":
		// "0" / "0.0" is a permitted disable-sentinel when AllowZero is
		// set, even outside the [min..max] range (mirrors the int case).
		f, err := strconv.ParseFloat(v, 64)
		if err != nil {
			return fmt.Sprintf("expected float, got %q", v)
		}
		if e.AllowZero && f == 0 {
			return ""
		}
		if e.MinFloat != nil && f < *e.MinFloat {
			return fmt.Sprintf("value %s is below minimum %s", v, trimFloat(*e.MinFloat))
		}
		if e.MaxFloat != nil && f > *e.MaxFloat {
			return fmt.Sprintf("value %s is above maximum %s", v, trimFloat(*e.MaxFloat))
		}
	case "duration":
		// "0s" is a permitted disable-sentinel when AllowZero is set,
		// even outside the [min..max] range.
		if e.AllowZero && (v == "0" || v == "0s") {
			return ""
		}
		d, err := time.ParseDuration(durationCanonical(v))
		if err != nil {
			return fmt.Sprintf("expected duration (e.g. '60m'), got %q: %v", v, err)
		}
		if e.MinDuration != "" {
			min, err := time.ParseDuration(durationCanonical(e.MinDuration))
			if err == nil && d < min {
				return fmt.Sprintf("value %s is below minimum %s", v, e.MinDuration)
			}
		}
		if e.MaxDuration != "" {
			max, err := time.ParseDuration(durationCanonical(e.MaxDuration))
			if err == nil && d > max {
				return fmt.Sprintf("value %s is above maximum %s", v, e.MaxDuration)
			}
		}
	case "bool":
		if v != "true" && v != "false" {
			return fmt.Sprintf("expected bool 'true' or 'false', got %q", v)
		}
	case "string":
		if len(e.ValidValues) > 0 {
			for _, vv := range e.ValidValues {
				if v == vv {
					return ""
				}
			}
			return fmt.Sprintf("value %q is not one of %v", v, e.ValidValues)
		}
	case "string-array":
		// We accept the rendered "[a, b]" or unbracketed forms; deep
		// validation would require knowing element semantics. v0.70.0
		// only checks the rendering shape.
		// (No-op.)
	default:
		return fmt.Sprintf("schema: unknown type %q (programming error)", e.Type)
	}
	return ""
}

// durationCanonical maps user-friendly extended units ("7d", "30d") to
// time.ParseDuration-acceptable shapes (Go's stdlib doesn't recognize
// "d"). Everything else is passed through verbatim.
func durationCanonical(s string) string {
	if strings.HasSuffix(s, "d") {
		n := strings.TrimSuffix(s, "d")
		if v, err := strconv.Atoi(n); err == nil {
			return fmt.Sprintf("%dh", v*24)
		}
	}
	return s
}

// ParseDuration parses a config duration value, honoring the extended
// "d" (days) suffix that defaults.toml uses ("7d", "30d", "365d") and
// that Go's time.ParseDuration does not recognize. Exported so other
// packages (e.g. internal/retention) can read duration-typed config
// values consistently with how SchemaValidate range-checks them.
func ParseDuration(s string) (time.Duration, error) {
	return time.ParseDuration(durationCanonical(s))
}
